baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://matthieupetite.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


# language settings
lang: fr 
languages: ["en", "fr"] 
default_lang: "fr"
exclude_from_localization: ["assets/css", "assets/img"]
parallel_localization: true



# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-polyglot

paginate: 5
paginate_path: "/page/:num"


# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
  - scope:
      path: '_post'
    values:
      permalink: /:basename:output_ext
  - scope:
      path: '_experiences'
      type: "experiences"
    values:
      layout: "experience"

include:
  - _pages


# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed

collections:
  experiences:
    output: true
    permalink: /:collection/:path
  certifications:
    output: false
  competences:
    output: false

