#-------------------------------
# General Site Settings
title: Matthieu Petite
logo: logo2.png # You can add own logo.
description: Bienvenu sur mon blog Tech, Cloud, et DevOps


#-------------------------------
# Author Settings
author:
  name: Matthieu Petite
  image: 01.jpg
  say-hello: Bonjour, je suis <strong>Matthieu Petite</strong>
  bio: Techno, Tips, et articles à propos du <strong>Cloud</strong>, <strong>Container</strong>, <strong>Microsoft</strong>, et du dev. Je partage des tutos, des ressources et mes idées. J'adore la <a href="#">grimpe</a>, le <a href="#">kite</a>, et les bières entre amis .


#-------------------------------
# Contact links
twitter: https://twitter.com/matthieu_petite # Add your Twitter handle
facebook: https://facebook.com/matthieu.petite # Add your Facebook handle
github: https://github.com/matthieupetite/ # Add your github handle
instagram: https://www.instagram.com/m4oppia/ # Add your Instagram handle


#-------------------------------
# Comment Section (Disqus)
#disqus-identifier: matthieu-petite-blog # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: m4oppia # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: G-3N0YD35HJK # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
